version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=u!know@this123game
      - MYSQL_DATABASE=u!know@this123game234
      - APACHE_URL=http://apache:8008
    networks:
      - my-net
    ports:
      - "4000:3306"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/

  flask:
    build:
      context: .
    container_name: flask-container
    restart: always
    ports:
      - "13680:5000"
    volumes:
      - ./main:/usr/src/app
    networks:
      - my-net
    environment: 
      - MYSQL_URL=http://mysql:4000
    links:
      - mysql
    depends_on:
      - mysql

networks:
  my-net:
    driver: bridge